const fs=require('node:fs');const file='outputs/dairy-factory/dist/js/app.js';let s=fs.readFileSync(file,'utf8');
const r=(a,b)=>{if(!s.includes(a))throw Error('Missing target: '+a.slice(0,100));s=s.replace(a,b);};
const section=(name,next,body)=>{const a=s.indexOf('  function '+name+'('),b=s.indexOf('  function '+next+'(',a);if(a<0||b<0)throw Error(name);s=s.slice(0,a)+body+'\n'+s.slice(b);};
r('const E=DairyEngine,L=DairyLevels,S=DairyStorage;', 'const E=DairyEngine,L=DairyLevels,S=DairyStorage,A=DairyAcademy,Art=DairyArt,P=DairyProgress,MAX=L.levels.length;');
r('instructionsOpen:false','instructionsOpen:false,academyCategory:"variables",example:0,lab:false,examAnswers:[null,null,null],examFeedback:null,examReady:false');
r("concepts:'Manual de campo'","concepts:'Academia'");
s=s.replaceAll('Dairy Factory','La Vía Láctea').replaceAll('PRODUCTION CHALLENGE','ESCUELA DE PRODUCCIÓN').replaceAll('v1.0','v2.0');
s=s.replaceAll("'<small>12</small>'","`<small>${MAX}</small>`").replaceAll('total.completed===12','total.completed===MAX').replaceAll('total.completed/12','total.completed/MAX').replaceAll('total.stars===36','total.stars===MAX*3');
s=s.replaceAll(' / 36',' / ${MAX*3}').replaceAll(' de 12 misiones',' de ${MAX} misiones').replaceAll(' / 12',' / ${MAX}').replaceAll('Ver las 12 misiones','Ver las ${MAX} misiones').replaceAll('L.levels[11]','L.levels[MAX-1]');
s=s.replaceAll('l.id===12','l.id===MAX').replaceAll('state.level.id===12','state.level.id===MAX').replaceAll('maximum:12','maximum:MAX');
r('done===4','done===w.ids.length');s=s.replaceAll('${done} / 4 misiones','${done} / ${w.ids.length} misiones');
r('<span class="brand-mark">🥛</span>','<span class="brand-mark">${Art.product("Leche fresca")}</span>');
r('<div class="tip-strip"><span>💡</span>', '<section class="home-living"><div><p class="eyebrow">DE LA GRANJA AL CLIENTE</p><h2>Cada estación cuenta.</h2><p>Recibe, organiza y despacha. Detrás de cada buen turno hay una buena decisión.</p><button class="text-button" data-nav="concepts">Entrar a la Academia →</button></div>${Art.scene()}</section><div class="tip-strip"><span>💡</span>');
r('<span class="world-icon">${w.icon}</span>', '<span class="world-icon">${worldArt(w.id)}</span>');
const worldStart=s.indexOf('  function worldCard(');s=s.slice(0,worldStart)+`  function worldArt(id){return id===1?Art.product('Leche fresca'):id===2?Art.machine():id===3?Art.truck():Art.medal();}\n`+s.slice(worldStart);
section('concepts','settings',`  function concepts(){shell(DairyAcademyUI.render(state.data,state.academyCategory,state.example,state.lab));}
  function openConcept(id){const before=P.achievements.filter(a=>a.earned(state.data)).map(a=>a.id);if(!P.visit(state.data,id))return;modal(DairyAcademyUI.concept(id));if(state.view==='concepts')concepts();const fresh=P.achievements.filter(a=>a.earned(state.data)&&!before.includes(a.id));if(fresh.length)toast('Logro: '+fresh.map(a=>a.name).join(', '));}
  function examIntro(){shell(DairyAcademyUI.exam(state.level,state.examAnswers,state.examFeedback));}
  function formalTable(l){return '<section class="panel academic-orders"><h2>Orden de dirección · '+l.notation+'</h2><p>Todos los tiempos son minutos desde las 08:00.</p><div class="table-scroll"><table><thead><tr><th>Job</th><th>pj</th><th>rj</th><th>dj</th><th>wj</th></tr></thead><tbody>'+l.jobs.map(j=>'<tr><td>'+j.id+' · '+j.product+'</td><td>'+j.p+'</td><td>'+j.r+'</td><td>'+j.d+'</td><td>'+j.w+'</td></tr>').join('')+'</tbody></table></div></section>';}
  function floor(l){return '<section class="factory-floor"><div class="floor-label"><p class="eyebrow">LA PLANTA EN VIVO</p><b id="floor-state">Lista para tu plan</b></div><div class="floor-machines">'+Array.from({length:l.machines},(_,m)=>'<div class="floor-machine" data-live-machine="'+m+'">'+Art.machine(m)+'<span>Línea '+String.fromCharCode(65+m)+'</span></div>').join('')+'</div><div class="dispatch"><div class="dispatch-products">'+l.jobs.map(j=>'<span data-dispatch="'+j.id+'" hidden>'+Art.product(j.product)+'<b>'+j.id+' ✓</b></span>').join('')+'</div>'+Art.truck()+'<span>Zona de despacho</span></div></section>';}
`);
// Preserve the same machine and job data; only the presentation changes.
r("shell(title('12 MISIONES · 3 MUNDOS'", "shell(title(MAX+' MISIONES · UNA FÁBRICA POR DESCUBRIR'");
r('<span class="world-icon">${w.icon}</span>', '<span class="station-art">${worldArt(w.id)}</span>');
r('${w.ids.filter(id=>state.data.results[id]).length} / 4 completadas','${w.ids.filter(id=>state.data.results[id]).length} / ${w.ids.length} completadas');
r('<span class="level-number">${String(id).padStart(2,\'0\')}</span>', '<span class="level-number">${String(id).padStart(2,\'0\')}</span><span class="level-product">${Art.product(l.jobs[0].product)}</span>');
r("const medals=[['🌱'", "const legacyMedals=[['🌱'");
const medalBegin=s.indexOf('    const legacyMedals='),medalEnd=s.indexOf('\n',medalBegin);
s=s.slice(0,medalBegin)+"    const medals=P.achievements.map(a=>[Art.medal(),a.name,a.earned(state.data),a.description]);"+s.slice(medalEnd);
r("state.data.lastLevel=level.id;S.save(state.data);render();", "state.data.lastLevel=level.id;state.examAnswers=[null,null,null];state.examFeedback=null;state.examReady=!level.formal;P.discover(state.data,level.id);S.save(state.data);render();");
r('const l=state.level,schedule=currentSchedule(),o=E.OBJECTIVES[l.objective];', "const l=state.level;if(l.formal&&!state.examReady){examIntro();return;}const schedule=currentSchedule(),o=E.OBJECTIVES[l.objective];");
r('<small>Objetivo: minimizar <b>${o.symbol}</b> · ${o.label}</small>', '<small>🎯 ${l.formal?l.notation:A.goals[l.objective][0]}</small><button class="concept-link" data-concept="${l.objective}">📘 Concepto relacionado: ${A.goals[l.objective][1]} ⓘ</button>');
r('${tutorial(schedule)}${learningPanel(schedule)}', '${floor(l)}${l.formal?formalTable(l):\'\'}${tutorial(schedule)}${learningPanel(schedule)}');
r('<span>${o.symbol}</span><strong>', '<span>${l.formal?o.symbol:\'TU META\'}</span><strong>');
r('${o.label} · menos es mejor','${A.goals[l.objective][1]} · menos es mejor');
r('<span class="job-icon">${j.icon}</span>', '<span class="job-icon">${Art.product(j.product)}</span>');
r('<span class="job-duration"><b>${j.p}</b> min <small>de proceso</small></span>', '<span class="job-duration" title="Tiempo de procesamiento — pj"><small>Tarda</small> <b>${j.p}</b> min <span class="info-dot" aria-label="Tiempo de procesamiento pj">ⓘ</span></span>');
r('<span>Disponible <b>${time(j.r)}</b></span>','<span title="Momento de disponibilidad — rj">Disponible desde <b>${time(j.r)}</b></span>');
r('<span>Entrega <b>${time(j.d)}</b></span>','<span title="Hora prometida de entrega — dj">Entrega <b>${time(j.d)}</b></span>');
r('<span>Prioridad <b title="Peso ${j.w}">${\'★\'.repeat(j.w)} <small>×${j.w}</small></b></span>', '<span title="Importancia del pedido — wj. No son estrellas de rendimiento.">Prioridad ⓘ <b>${j.w>=4?\'Alta\':j.w>=2?\'Media\':\'Normal\'} <small>×${j.w}</small></b></span>');
r('<span class="job-placement">', '<span class="order-status" data-order-status="${j.id}"></span><span class="job-placement">');
r('<span class="machine-badge">⚙</span>', '<span class="machine-badge">${Art.machine(m)}</span>');
r('<span>${j.icon}</span><b>${id}</b>', '<span class="queue-product">${Art.product(j.product)}</span><b>${id}</b>');
r('<span>${o.id}</span><small>${o.p}′</small>', '<span class="gantt-product">${Art.product(o.product)}</span><span>${o.id}</span><small>${o.p}′</small>');
r('title="${o.id}: ${time(o.start)}–${time(o.end)}', 'title="${o.id} · ${o.product} · Inicio ${time(o.start)} · Fin ${time(o.end)} · Duración ${o.p} min · Entrega ${time(o.d)} · Retraso ${o.T} min');
r('<p>${l.lesson}</p>', '<p>${l.formal?l.lesson:A.naturalLessons[l.id-1]}</p><button class="text-button" data-concept="${l.objective}">Entender el concepto en la Academia →</button>');
r('T${late.id.slice(1)} = max(0, ${late.C} − ${late.d}) = <b>${late.T} min</b>.','Su retraso fue de <b>${late.T} min</b>.');
r('<small>TU SOLUCIÓN · ${o.symbol}</small>', '<small>TU SOLUCIÓN${l.formal?\' · \'+o.symbol:\'\'}</small>');
r('<details class="score-detail"><summary>Ver métricas y desglose de puntos</summary>', '<div class="result-jobs">${schedule.operations.map(job=>`<div class="result-job ${l.show.includes(\'d\')&&job.T?\'late\':\'on-time\'}">${Art.product(job.product)}<b>${job.id}</b><span>${l.show.includes(\'d\')&&job.T?\'⚠ +\'+job.T+\' min\':\'✓ Listo\'}</span></div>`).join(\'\')}</div><div class="new-concepts"><b>📘 Conexión con la Academia</b><p>${A.entries.filter(e=>e.unlockedAt===l.id).map(e=>`<button data-concept="${e.id}">${e.simpleName} ↗</button>`).join(\'\')||\'Sigue explorando los conceptos de este turno.\'}</p></div>${l.id===MAX&&!r.practice?`<section class="graduation">${Art.medal()}<div><p class="eyebrow">🎓 JEFE DE PRODUCCIÓN</p><h3>Maestro de la Secuenciación</h3><p>Has completado todos los desafíos de La Vía Láctea. Ahora sabes conectar tus decisiones con el lenguaje de producción.</p></div></section>`:\'\'}<details class="score-detail"><summary>Ver métricas académicas y desglose de puntos</summary>');
r("state.result={schedule,benchmark,evaluation};S.record", "evaluation.hintsUsed=state.hints;evaluation.allOnTime=state.level.show.includes('d')&&schedule.metrics.lateCount===0;state.result={schedule,benchmark,evaluation};S.record");
r("function startProduction(){clearTimeout", "function startProduction(){if(state.level.formal&&!state.examReady)return false;clearTimeout");
r("function currentSchedule(){return", "function currentSchedule(){return");
r("if(el.dataset.nav){", "if(el.dataset.concept){openConcept(el.dataset.concept);return;}\n    if(el.dataset.category){state.academyCategory=el.dataset.category;render();return;}\n    if(el.dataset.example!=null){state.example=Number(el.dataset.example);render();return;}\n    if(el.dataset.nav){");
r("if(name==='close'){closeModal();return;}", "if(name==='close'){closeModal();return;}\n    if(name==='lab-toggle'){state.lab=!state.lab;render();return;}\n    if(name==='exam-check'){if(state.examAnswers.some(a=>a==null))return;state.examFeedback=A.grade(state.examAnswers);render();return;}\n    if(name==='exam-retry'){state.examAnswers=[null,null,null];state.examFeedback=null;render();return;}\n    if(name==='exam-continue'){if(!state.examFeedback)return;state.examReady=true;render();window.scrollTo(0,0);return;}");
r("document.addEventListener('change',event=>{const key=", "document.addEventListener('change',event=>{if(event.target.dataset.question!=null){state.examAnswers[Number(event.target.dataset.question)]=Number(event.target.value);const check=app.querySelector('[data-action=\"exam-check\"]');if(check)check.disabled=state.examAnswers.some(a=>a==null);return;}const key=");
r("if(!state.level||state.view!=='game'||state.running||state.guide)","if(!state.level||state.view!=='game'||state.running||state.guide||(state.level.formal&&!state.examReady))");
// Natural names in optional per-job inspection; formal relations remain available in tooltips.
r('Cj · finalización','Hora de finalización');r('Fj = Cj − rj','Tiempo dentro del sistema');r('Lj = Cj − dj','Diferencia frente a la promesa');r('Tj = max(0, Lj)','Tiempo de retraso');r('wj × Cj','Finalización por importancia');r('wj × Tj','Retraso por importancia');
r('<span>${o.icon}</span><button', '<span class="inspect-art">${Art.product(o.product)}</span><button');
r("const clock=document.getElementById('simulation-clock');if(!clock)return;clock.textContent=time(t);", "const clock=document.getElementById('simulation-clock');if(!clock)return;clock.textContent=time(t);const floorState=document.getElementById('floor-state');if(floorState)floorState.textContent='Turno en marcha · '+time(t);\n    schedule.operations.forEach(o=>{const done=t>=o.end,live=document.querySelector('[data-order-status=\"'+o.id+'\"]'),box=document.querySelector('[data-dispatch=\"'+o.id+'\"]');if(box)box.hidden=!done;if(live){const risk=state.level.show.includes('d')&&!done&&t>=o.d-10,late=state.level.show.includes('d')&&t>o.d;live.textContent=done?'✓ Producción terminada':late?'! Pedido retrasado':risk?'⚠ Entrega cercana':t>=o.start?'⚙ En producción':'';live.className='order-status '+(done?'done':late?'late':risk?'risk':'');}});");
r("el.classList.toggle('working',!!active);", "el.classList.toggle('working',!!active);document.querySelector('[data-live-machine=\"'+m+'\"]')?.classList.toggle('working',!!active);");
fs.writeFileSync(file,s);
