const fs=require('node:fs');
const file='outputs/dairy-factory/dist/js/app.js';
let s=fs.readFileSync(file,'utf8');
const replace=(from,to)=>{if(!s.includes(from))throw Error('Missing target '+from.slice(0,90));s=s.replace(from,to);};
replace("simulation.stop();state.level=level;","simulation.stop();clearTimeout(guideTimer);state.guide=null;resetIdle();state.level=level;");
replace('${tutorial(schedule)}<div class="game-layout">','${tutorial(schedule)}${learningPanel(schedule)}<div class="game-layout">');
replace('Cada pista resta 100 puntos.<br>Las estrellas no cambian.</small></section>', 'Cada pista resta 100 puntos.<br>Las estrellas no cambian.</small><button class="guided-answer" data-action="guide-start" ${state.running||state.guide?\'disabled\':\'\'}>▷ Ver respuesta paso a paso</button><small>Una demostración explicada, a tu ritmo.</small></section>');
replace("function navigate(view){simulation.stop();", "function navigate(view){simulation.stop();clearTimeout(guideTimer);state.guide=null;resetIdle();");
replace("function moveJob(id,m,index){\n    if(state.running", "function moveJob(id,m,index){\n    if(state.guide)return false;resetIdle();\n    if(state.running");
replace("function removeJob(id){if(state.running)return;", "function removeJob(id){if(state.running||state.guide)return;resetIdle();");
replace("function hint(){if(state.hints>=3||state.running)return;", "function hint(){if(state.hints>=3||state.running)return;resetIdle();");
replace("function startProduction(){const schedule=", "function startProduction(){clearTimeout(guideTimer);if(state.guide)state.guide.playing=false;resetIdle();const schedule=");
replace("if(name==='clear'&&!state.running)", "if(name==='guide-start'){beginGuide();return;}\n    if(name==='guide-next'){clearTimeout(guideTimer);state.guide.playing=false;guideStep(1);return;}\n    if(name==='guide-back'){clearTimeout(guideTimer);state.guide.playing=false;guideStep(-1);return;}\n    if(name==='guide-play'){playGuide();return;}\n    if(name==='guide-restore'){restoreGuide();return;}\n    if(name==='dismiss-help'){resetIdle();return;}\n    if(name==='clear'&&!state.running&&!state.guide)");
replace("if(el.dataset.job&&!state.running)","if(el.dataset.job&&!state.running&&!state.guide)");
replace("if(el.dataset.move&&!state.running)","if(el.dataset.move&&!state.running&&!state.guide)");
replace("const m=state.queues.findIndex(q=>q.includes(el.dataset.move))", "resetIdle();const m=state.queues.findIndex(q=>q.includes(el.dataset.move))");
replace("if(!el||state.running){event.preventDefault();return;}","if(!el||state.running||state.guide){event.preventDefault();return;}");
replace("if(target&&!state.running)","if(target&&!state.running&&!state.guide)");
replace("${l.id===12?'Ver mi progreso':'Siguiente misión →'}", "${r.practice&&!state.data.results[l.id]?'Ahora me toca':l.id===12?'Ver mi progreso':'Siguiente misión →'}");
replace("if(name==='next'){closeModal();if(state.level.id===12)","if(name==='next'){closeModal();if(state.revealed&&!state.data.results[state.level.id]){startLevel(state.level.id);return;}if(state.level.id===12)");
replace("function solution(){closeModal();const b=", "function solution(){closeModal();clearTimeout(guideTimer);state.guide=null;const b=");
replace("if(!state.level||state.view!=='game'||state.running)","if(!state.level||state.view!=='game'||state.running||state.guide)");
replace("state.queues=input.queues.map(q=>[...q]);", "resetIdle();state.queues=input.queues.map(q=>[...q]);");
replace("hasta 1.000 por entregas a tiempo,", "hasta 1.000 por entregas a tiempo (1.000 fijos en misiones que aún no muestran fechas),");
fs.writeFileSync(file,s);
