const fs=require('node:fs'),p='outputs/dairy-factory/dist/js/app.js';let s=fs.readFileSync(p,'utf8');const r=(a,b)=>{if(!s.includes(a))throw Error('Missing '+a.slice(0,80));s=s.replace(a,b);};
r('examReady:false','examReady:false,modalBack:null');
r("function closeModal(){document.getElementById('modal').close();previousFocus?.focus?.();}","function closeModal(){const d=document.getElementById('modal');if(state.modalBack){d.innerHTML=state.modalBack;state.modalBack=null;d.querySelector('button')?.focus();return;}d.close();previousFocus?.focus?.();}");
r("if(!P.visit(state.data,id))return;modal(DairyAcademyUI.concept(id));", "if(!P.visit(state.data,id))return;const dialog=document.getElementById('modal');if(dialog.open&&dialog.querySelector('.result-hero'))state.modalBack=dialog.innerHTML;modal(DairyAcademyUI.concept(id));");
r("function concepts(){shell(DairyAcademyUI.render(state.data,state.academyCategory,state.example,state.lab));}", "function concepts(){shell((state.level?'<button class=\"secondary return-turn\" data-action=\"return-turn\">← Volver a mi turno · '+state.level.title+'</button>':'')+DairyAcademyUI.render(state.data,state.academyCategory,state.example,state.example===99?false:state.lab));}");
r("if(name==='lab-toggle')", "if(name==='return-turn'){navigate('game');return;}\n    if(name==='lab-toggle')");
r("function navigate(view){simulation.stop();clearTimeout(guideTimer);state.guide=null;", "function navigate(view){simulation.stop();clearTimeout(guideTimer);if(state.guide){state.queues=state.guide.snapshot;state.selected=state.guide.selection;}state.guide=null;state.modalBack=null;");
r("function next(){if(!state.guide?.playing)return;guideStep(1);", "function next(){if(!state.guide?.playing)return;if(document.hidden||document.getElementById('modal').open){guideTimer=setTimeout(next,1000);return;}guideStep(1);");
r("for(const o of schedule.operations){const el=document.querySelector(`[data-operation=\"${o.id}\"]`);if(!el)continue;el.classList.toggle('processing',t>=o.start&&t<o.end);el.classList.toggle('completed',t>=o.end);el.querySelector('.block-progress').style.width=Math.min(1,Math.max(0,(t-o.start)/o.p))*100+'%';}","for(const o of schedule.operations)document.querySelectorAll(`[data-operation=\"${o.id}\"]`).forEach(el=>{el.classList.toggle('processing',t>=o.start&&t<o.end);el.classList.toggle('completed',t>=o.end);el.querySelector('.block-progress').style.width=Math.min(1,Math.max(0,(t-o.start)/o.p))*100+'%';});");
// Keyboard navigation for the Academy tabs, avoiding mouse-only categories.
r("document.addEventListener('keydown',event=>{if(event.key==='Escape'", "document.addEventListener('keydown',event=>{if(event.target.matches?.('[data-category]')&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const ids=A.categories.map(c=>c.id),current=ids.indexOf(state.academyCategory),next=event.key==='Home'?0:event.key==='End'?ids.length-1:(current+(event.key==='ArrowRight'?1:-1)+ids.length)%ids.length;state.academyCategory=ids[next];render();document.querySelector('[data-category=\"'+ids[next]+'\"]')?.focus();return;}if(event.key==='Escape'");
r("state.example===99?false:state.lab","state.lab");
fs.writeFileSync(p,s);
